GET http://localhost:8082
### products -> (endpoint or resource name)
GET http://localhost:8082/products 
###
GET http://localhost:8082/users/1234/posts/5678
###
GET http://localhost:8082/currencies
###
# GET http://localhost:8082/currencies?min_value=0.01&max_value=2000
###
GET http://localhost:8082/currencies?min_value=0.01
###
GET http://localhost:8082/currencies/abcd
###
GET http://localhost:8082/users
Authorization: LetMe
###
GET http://localhost:8082/users/6607d086-7159-4c26-beb1-280c9f9cbf35
###
GET http://localhost:8082/users/search?gender=male&age=49
###
GET http://localhost:8082/users/search?gender=male
Authorization: LetMeIn
###
GET http://localhost:8082/users/search?age=adi
###
GET http://localhost:8082/users/search
###
POST http://localhost:8082/blogs/new
Content-Type: application/json

{
    "title": "Kodaikanal",
    "authors": [
        {
            "fullName": "Vivek Nigam",
            "email": "vivek@abcd.com",
            "twitterHandle": "@_viveknigam_",
            "image": "https://w7.pngwing.com/pngs/205/731/png-transparent-default-avatar.png"
        }
    ]
}
###
GET  http://localhost:8082/blogs
###
GET  http://localhost:8082/blogs/675da835154a3589642f7bd4
###
PATCH  http://localhost:8082/blogs/675db71f90555ff022471737
Content-Type: application/json

{
    "content": "Famous for its' tea"
}

###
DELETE  http://localhost:8082/blogs/675da835154a3589642f7bd4
###
GET  http://localhost:8082/blogs/search?title=va&author=vivek@resuminator.in
###
GET  http://localhost:8082/blogs/search?title=m
###
GET  http://localhost:8082/blogs/search?author=vivek@resuminator.in
###
GET  http://localhost:8082/blogs/search