GET http://localhost:8082
### products -> (endpoint or resource name)
GET http://localhost:8082/products 
###
GET http://localhost:8082/users/1234/posts/5678
###
GET http://localhost:8082/currencies
###
POST http://localhost:8082/currencies
###
GET http://localhost:8082/currencies/abcd